# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Yahoo-Search
version:      1.6.9
version_from: lib/Yahoo/Search.pm
installdirs:  site
requires:
    HTTP::Request:                 0
    LWP::UserAgent:                0
    URI:                           0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.30
